[project]
name = "pyzotero-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.0",
    "pyyaml>=6.0.2",
    "pyzotero>=1.6.11",
    "tabulate>=0.9.0",
]
